version: "3"

networks:
  common.network:
    driver: bridge

volumes:
  mongo.one.vol:
    name: "mongo.one.vol"

  mongo.two.vol:
    name: "mongo.two.vol"

  mongo.three.vol:
    name: "mongo.three.vol"

services:
  mongo.one.db:
    container_name: mongo.one.db
    image: mongo:6
    networks:
      common.network:
    ports:
      - 2717:27017
    volumes:
      - ./dockerdata/mongo.one.vol:/data/db
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs"]

  mongo.two.db:
    container_name: mongo.two.db
    image: mongo:6
    networks:
      common.network:
    ports:
      - 2718:27017
    depends_on:
      - mongo.one.db
    volumes:
      - ./dockerdata/mongo.two.vol:/data/db
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs"]

  mongo.three.db:
    container_name: mongo.three.db
    image: mongo:6
    networks:
      common.network:
    ports:
      - 2719:27017
    depends_on:
      - mongo.one.db
    volumes:
      - ./dockerdata/mongo.three.vol:/data/db
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs"]
